.PHONY: all clean

all: piekarnia1.x piekarnia2.x paterson.x


piekarnia1.x: piekarnia1.c


piekarnia1.x: piekarnia1.c
	gcc piekarnia1.c -lpthread -o piekarnia1.x 

piekarnia2.x: piekarnia2.c


piekarnia2.x: piekarnia2.c
	gcc piekarnia2.c -lpthread -o piekarnia2.x 

paterson.x: paterson.c


paterson.x: paterson.c
	gcc paterson.c -lpthread -o paterson.x 



clean:
	$(RM) *.o *.x *.a



